apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: test-app
  namespace: argocd
spec:
  source:
    repoURL: https://github.com/MichaelHan38/homelab.git
    targetRevision: HEAD
    path: argocd-config/test-app
  destination: 
    server: https://kubernetes.default.svc
    namespace: app
  syncPolicy:
    syncOptions:
    - CreateNamespace=true

