apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: test-app
  namespace: argo-cd
spec:
  project:
    default

  source:
    repoURL: https://github.com/MichaelHan38/homelab.git
    targetRevision: HEAD
    path: argocd-config/test-app
  destination: 
    server: https://kubernetes.default.svc
    namespace: app
    
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true