apiVersion: v1
kind: PersistentVolume
metadata:
  name: media-hdd-pv
  namespace: media
  labels:
    type: hdd
spec:
  volumeMode: Filesystem
  storageClassName: "media-hdd"
  capacity:
    storage: 10Mi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  local:
    path: /mnt/hdd-1/media
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - osboxes
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: media-ssd-pv
  namespace: media
  labels:
    type: hdd
spec:
  volumeMode: Filesystem
  storageClassName: "media-ssd"
  capacity:
    storage: 10Mi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  local:
    path: /mnt/ssd-1/media
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - osboxes
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich-lib-pv-claim
  namespace: media
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: "media-hdd"
  resources:
    requests:
      storage: 1Mi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich-thum-pv-claim
  namespace: media
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: "media-ssd"
  resources:
    requests:
      storage: 1Mi